#ifndef EEPROM_MANAGE_H
#define EEPROM_MANAGE_H

/*** EEPROM ADDR*/
#define EEPROM_ADDR_FOG_STATUS 4095
#define EEPROM_ADDR_DVT_TEST_1 4092
#define EEPROM_ADDR_DVT_TEST_2 4093
#define EEPROM_ADDR_DVT_TEST_3 4094
#define EEPROM_ADDR_OUTPUT_FN  4090 
#define EEPROM_ADDR_SELECT_FN  4091
#define EEPROM_ADDR_REG_VALUE  4089
/** for fog parameter**/
#define EEPROM_ADDR_PARAMETER_EXIST 1
#define EEPROM_BASEADDR_Z           2 // 2 ~ 65, len = 64
#define EEPROM_BASEADDR_X           66 //66 ~ 129, len = 64
#define EEPROM_BASEADDR_Y           130 //130 ~ 193, len = 64
#define EEPROM_BASEADDR_OUT_CONFIG  194 //194 ~ 209, len = 16
#define EEPROM_BASEADDR_MIS_CALI    210 //210 ~ 241, len = 32

// z axis
#define EEPROM_ADDR_MOD_FREQ_Z        EEPROM_BASEADDR_Z
#define EEPROM_ADDR_WAIT_CNT_Z        EEPROM_BASEADDR_Z+1
#define EEPROM_ADDR_ERR_AVG_Z         EEPROM_BASEADDR_Z+2
#define EEPROM_ADDR_MOD_AMP_H_Z       EEPROM_BASEADDR_Z+3
#define EEPROM_ADDR_MOD_AMP_L_Z       EEPROM_BASEADDR_Z+4
#define EEPROM_ADDR_ERR_TH_Z          EEPROM_BASEADDR_Z+5
#define EEPROM_ADDR_ERR_OFFSET_Z      EEPROM_BASEADDR_Z+6
#define EEPROM_ADDR_POLARITY_Z        EEPROM_BASEADDR_Z+7
#define EEPROM_ADDR_CONST_STEP_Z      EEPROM_BASEADDR_Z+8
#define EEPROM_ADDR_FPGA_Q_Z          EEPROM_BASEADDR_Z+9
#define EEPROM_ADDR_FPGA_R_Z          EEPROM_BASEADDR_Z+10
#define EEPROM_ADDR_GAIN1_Z           EEPROM_BASEADDR_Z+11
#define EEPROM_ADDR_GAIN2_Z           EEPROM_BASEADDR_Z+12
#define EEPROM_ADDR_FB_ON_Z           EEPROM_BASEADDR_Z+13
#define EEPROM_ADDR_DAC_GAIN_Z        EEPROM_BASEADDR_Z+14
#define EEPROM_ADDR_DATA_DELAY_Z      EEPROM_BASEADDR_Z+15
#define EEPROM_ADDR_SF_0_Z            EEPROM_BASEADDR_Z+16
#define EEPROM_ADDR_SF_1_Z            EEPROM_BASEADDR_Z+17
#define EEPROM_ADDR_SF_2_Z            EEPROM_BASEADDR_Z+18
#define EEPROM_ADDR_SF_3_Z            EEPROM_BASEADDR_Z+19
#define EEPROM_ADDR_SF_4_Z            EEPROM_BASEADDR_Z+20
#define EEPROM_ADDR_SF_5_Z            EEPROM_BASEADDR_Z+21
#define EEPROM_ADDR_SF_6_Z            EEPROM_BASEADDR_Z+22
#define EEPROM_ADDR_SF_7_Z            EEPROM_BASEADDR_Z+23
#define EEPROM_ADDR_SF_8_Z            EEPROM_BASEADDR_Z+24
#define EEPROM_ADDR_SF_9_Z            EEPROM_BASEADDR_Z+25
#define EEPROM_ADDR_TMIN_Z            EEPROM_BASEADDR_Z+26
#define EEPROM_ADDR_TMAX_Z            EEPROM_BASEADDR_Z+27
#define EEPROM_ADDR_SFB_Z             EEPROM_BASEADDR_Z+28
#define EEPROM_ADDR_CUTOFF_Z          EEPROM_BASEADDR_Z+29
#define EEPROM_ADDR_BIAS_COMP_T1_Z    EEPROM_BASEADDR_Z+30
#define EEPROM_ADDR_BIAS_COMP_T2_Z    EEPROM_BASEADDR_Z+31
#define EEPROM_ADDR_SFB_1_SLOPE_Z     EEPROM_BASEADDR_Z+32
#define EEPROM_ADDR_SFB_1_OFFSET_Z    EEPROM_BASEADDR_Z+33
#define EEPROM_ADDR_SFB_2_SLOPE_Z     EEPROM_BASEADDR_Z+34
#define EEPROM_ADDR_SFB_2_OFFSET_Z    EEPROM_BASEADDR_Z+35
#define EEPROM_ADDR_SFB_3_SLOPE_Z     EEPROM_BASEADDR_Z+36
#define EEPROM_ADDR_SFB_3_OFFSET_Z    EEPROM_BASEADDR_Z+37
// x axis
#define EEPROM_ADDR_MOD_FREQ_X        EEPROM_BASEADDR_X
#define EEPROM_ADDR_WAIT_CNT_X        EEPROM_BASEADDR_X+1
#define EEPROM_ADDR_ERR_AVG_X         EEPROM_BASEADDR_X+2
#define EEPROM_ADDR_MOD_AMP_H_X       EEPROM_BASEADDR_X+3
#define EEPROM_ADDR_MOD_AMP_L_X       EEPROM_BASEADDR_X+4
#define EEPROM_ADDR_ERR_TH_X          EEPROM_BASEADDR_X+5
#define EEPROM_ADDR_ERR_OFFSET_X      EEPROM_BASEADDR_X+6
#define EEPROM_ADDR_POLARITY_X        EEPROM_BASEADDR_X+7
#define EEPROM_ADDR_CONST_STEP_X      EEPROM_BASEADDR_X+8
#define EEPROM_ADDR_FPGA_Q_X          EEPROM_BASEADDR_X+9
#define EEPROM_ADDR_FPGA_R_X          EEPROM_BASEADDR_X+10
#define EEPROM_ADDR_GAIN1_X           EEPROM_BASEADDR_X+11
#define EEPROM_ADDR_GAIN2_X           EEPROM_BASEADDR_X+12
#define EEPROM_ADDR_FB_ON_X           EEPROM_BASEADDR_X+13
#define EEPROM_ADDR_DAC_GAIN_X        EEPROM_BASEADDR_X+14
#define EEPROM_ADDR_DATA_DELAY_X      EEPROM_BASEADDR_X+15
#define EEPROM_ADDR_SF_0_X            EEPROM_BASEADDR_X+16
#define EEPROM_ADDR_SF_1_X            EEPROM_BASEADDR_X+17
#define EEPROM_ADDR_SF_2_X            EEPROM_BASEADDR_X+18
#define EEPROM_ADDR_SF_3_X            EEPROM_BASEADDR_X+19
#define EEPROM_ADDR_SF_4_X            EEPROM_BASEADDR_X+20
#define EEPROM_ADDR_SF_5_X            EEPROM_BASEADDR_X+21
#define EEPROM_ADDR_SF_6_X            EEPROM_BASEADDR_X+22
#define EEPROM_ADDR_SF_7_X            EEPROM_BASEADDR_X+23
#define EEPROM_ADDR_SF_8_X            EEPROM_BASEADDR_X+24
#define EEPROM_ADDR_SF_9_X            EEPROM_BASEADDR_X+25
#define EEPROM_ADDR_TMIN_X            EEPROM_BASEADDR_X+26
#define EEPROM_ADDR_TMAX_X            EEPROM_BASEADDR_X+27
#define EEPROM_ADDR_SFB_X             EEPROM_BASEADDR_X+28
#define EEPROM_ADDR_CUTOFF_X          EEPROM_BASEADDR_X+29
#define EEPROM_ADDR_BIAS_COMP_T1_X    EEPROM_BASEADDR_X+30
#define EEPROM_ADDR_BIAS_COMP_T2_X    EEPROM_BASEADDR_X+31
#define EEPROM_ADDR_SFB_1_SLOPE_X     EEPROM_BASEADDR_X+32
#define EEPROM_ADDR_SFB_1_OFFSET_X    EEPROM_BASEADDR_X+33
#define EEPROM_ADDR_SFB_2_SLOPE_X     EEPROM_BASEADDR_X+34
#define EEPROM_ADDR_SFB_2_OFFSET_X    EEPROM_BASEADDR_X+35
#define EEPROM_ADDR_SFB_3_SLOPE_X     EEPROM_BASEADDR_X+36
#define EEPROM_ADDR_SFB_3_OFFSET_X    EEPROM_BASEADDR_X+37
// y axis
#define EEPROM_ADDR_MOD_FREQ_Y        EEPROM_BASEADDR_Y
#define EEPROM_ADDR_WAIT_CNT_Y        EEPROM_BASEADDR_Y+1
#define EEPROM_ADDR_ERR_AVG_Y         EEPROM_BASEADDR_Y+2
#define EEPROM_ADDR_MOD_AMP_H_Y       EEPROM_BASEADDR_Y+3
#define EEPROM_ADDR_MOD_AMP_L_Y       EEPROM_BASEADDR_Y+4
#define EEPROM_ADDR_ERR_TH_Y          EEPROM_BASEADDR_Y+5
#define EEPROM_ADDR_ERR_OFFSET_Y      EEPROM_BASEADDR_Y+6
#define EEPROM_ADDR_POLARITY_Y        EEPROM_BASEADDR_Y+7
#define EEPROM_ADDR_CONST_STEP_Y      EEPROM_BASEADDR_Y+8
#define EEPROM_ADDR_FPGA_Q_Y          EEPROM_BASEADDR_Y+9
#define EEPROM_ADDR_FPGA_R_Y          EEPROM_BASEADDR_Y+10
#define EEPROM_ADDR_GAIN1_Y           EEPROM_BASEADDR_Y+11
#define EEPROM_ADDR_GAIN2_Y           EEPROM_BASEADDR_Y+12
#define EEPROM_ADDR_FB_ON_Y           EEPROM_BASEADDR_Y+13
#define EEPROM_ADDR_DAC_GAIN_Y        EEPROM_BASEADDR_Y+14
#define EEPROM_ADDR_DATA_DELAY_Y      EEPROM_BASEADDR_Y+15
#define EEPROM_ADDR_SF_0_Y            EEPROM_BASEADDR_Y+16
#define EEPROM_ADDR_SF_1_Y            EEPROM_BASEADDR_Y+17
#define EEPROM_ADDR_SF_2_Y            EEPROM_BASEADDR_Y+18
#define EEPROM_ADDR_SF_3_Y            EEPROM_BASEADDR_Y+19
#define EEPROM_ADDR_SF_4_Y            EEPROM_BASEADDR_Y+20
#define EEPROM_ADDR_SF_5_Y            EEPROM_BASEADDR_Y+21
#define EEPROM_ADDR_SF_6_Y            EEPROM_BASEADDR_Y+22
#define EEPROM_ADDR_SF_7_Y            EEPROM_BASEADDR_Y+23
#define EEPROM_ADDR_SF_8_Y            EEPROM_BASEADDR_Y+24
#define EEPROM_ADDR_SF_9_Y            EEPROM_BASEADDR_Y+25
#define EEPROM_ADDR_TMIN_Y            EEPROM_BASEADDR_Y+26
#define EEPROM_ADDR_TMAX_Y            EEPROM_BASEADDR_Y+27
#define EEPROM_ADDR_SFB_Y             EEPROM_BASEADDR_Y+28
#define EEPROM_ADDR_CUTOFF_Y          EEPROM_BASEADDR_Y+29
#define EEPROM_ADDR_BIAS_COMP_T1_Y    EEPROM_BASEADDR_Y+30
#define EEPROM_ADDR_BIAS_COMP_T2_Y    EEPROM_BASEADDR_Y+31
#define EEPROM_ADDR_SFB_1_SLOPE_Y     EEPROM_BASEADDR_Y+32
#define EEPROM_ADDR_SFB_1_OFFSET_Y    EEPROM_BASEADDR_Y+33
#define EEPROM_ADDR_SFB_2_SLOPE_Y     EEPROM_BASEADDR_Y+34
#define EEPROM_ADDR_SFB_2_OFFSET_Y    EEPROM_BASEADDR_Y+35
#define EEPROM_ADDR_SFB_3_SLOPE_Y     EEPROM_BASEADDR_Y+36
#define EEPROM_ADDR_SFB_3_OFFSET_Y    EEPROM_BASEADDR_Y+37

/** system cinfuguration parameter**/
#define EEPROM_ADDR_BAUDRATE          EEPROM_BASEADDR_OUT_CONFIG
#define EEPROM_ADDR_DATARATE          EEPROM_BASEADDR_OUT_CONFIG+1
#define EEPROM_ADDR_CLOCK             EEPROM_BASEADDR_OUT_CONFIG+2
#define EEPROM_ADDR_EXTWDT            EEPROM_BASEADDR_OUT_CONFIG+3
/** IMU Misalignment calibration*/
/**XLM*/
#define EEPROM_ADDR_CALI_AX           EEPROM_BASEADDR_MIS_CALI
#define EEPROM_ADDR_CALI_AY           EEPROM_BASEADDR_MIS_CALI+1
#define EEPROM_ADDR_CALI_AZ           EEPROM_BASEADDR_MIS_CALI+2
#define EEPROM_ADDR_CALI_A11          EEPROM_BASEADDR_MIS_CALI+3
#define EEPROM_ADDR_CALI_A12          EEPROM_BASEADDR_MIS_CALI+4
#define EEPROM_ADDR_CALI_A13          EEPROM_BASEADDR_MIS_CALI+5
#define EEPROM_ADDR_CALI_A21          EEPROM_BASEADDR_MIS_CALI+6
#define EEPROM_ADDR_CALI_A22          EEPROM_BASEADDR_MIS_CALI+7
#define EEPROM_ADDR_CALI_A23          EEPROM_BASEADDR_MIS_CALI+8
#define EEPROM_ADDR_CALI_A31          EEPROM_BASEADDR_MIS_CALI+9
#define EEPROM_ADDR_CALI_A32          EEPROM_BASEADDR_MIS_CALI+10
#define EEPROM_ADDR_CALI_A33          EEPROM_BASEADDR_MIS_CALI+11
/*** GYRO*/
#define EEPROM_ADDR_CALI_GX           EEPROM_BASEADDR_MIS_CALI+12
#define EEPROM_ADDR_CALI_GY           EEPROM_BASEADDR_MIS_CALI+13
#define EEPROM_ADDR_CALI_GZ           EEPROM_BASEADDR_MIS_CALI+14
#define EEPROM_ADDR_CALI_G11          EEPROM_BASEADDR_MIS_CALI+15
#define EEPROM_ADDR_CALI_G12          EEPROM_BASEADDR_MIS_CALI+16
#define EEPROM_ADDR_CALI_G13          EEPROM_BASEADDR_MIS_CALI+17
#define EEPROM_ADDR_CALI_G21          EEPROM_BASEADDR_MIS_CALI+18
#define EEPROM_ADDR_CALI_G22          EEPROM_BASEADDR_MIS_CALI+19
#define EEPROM_ADDR_CALI_G23          EEPROM_BASEADDR_MIS_CALI+20
#define EEPROM_ADDR_CALI_G31          EEPROM_BASEADDR_MIS_CALI+21
#define EEPROM_ADDR_CALI_G32          EEPROM_BASEADDR_MIS_CALI+22
#define EEPROM_ADDR_CALI_G33          EEPROM_BASEADDR_MIS_CALI+23

/**Global Variable for EEPROM*/
int EEPROM_Parameter_exist=0; 
//Output configuration
int EEPROM_BAUDRATE, EEPROM_DATARATE, EEPROM_SYSCLK, EEPROM_EXTWDT;
//Misalignment calibration
int EEPROM_CALI_AX, EEPROM_CALI_AY, EEPROM_CALI_AZ;
int EEPROM_CALI_A11, EEPROM_CALI_A12, EEPROM_CALI_A13;
int EEPROM_CALI_A21, EEPROM_CALI_A22, EEPROM_CALI_A23;
int EEPROM_CALI_A31, EEPROM_CALI_A32, EEPROM_CALI_A33;
int EEPROM_CALI_GX, EEPROM_CALI_GY, EEPROM_CALI_GZ;
int EEPROM_CALI_G11, EEPROM_CALI_G12, EEPROM_CALI_G13;
int EEPROM_CALI_G21, EEPROM_CALI_G22, EEPROM_CALI_G23;
int EEPROM_CALI_G31, EEPROM_CALI_G32, EEPROM_CALI_G33;

struct eeprom_obj{
    const uint32_t EEPROM_ADDR_MOD_FREQ        ;
    const uint32_t EEPROM_ADDR_WAIT_CNT        ;
    const uint32_t EEPROM_ADDR_ERR_AVG         ;
    const uint32_t EEPROM_ADDR_MOD_AMP_H       ;
    const uint32_t EEPROM_ADDR_MOD_AMP_L       ;
    const uint32_t EEPROM_ADDR_ERR_TH          ;
    const uint32_t EEPROM_ADDR_ERR_OFFSET      ;
    const uint32_t EEPROM_ADDR_POLARITY        ;
    const uint32_t EEPROM_ADDR_CONST_STEP      ;
    const uint32_t EEPROM_ADDR_FPGA_Q          ;
    const uint32_t EEPROM_ADDR_FPGA_R          ;
    const uint32_t EEPROM_ADDR_GAIN1           ;
    const uint32_t EEPROM_ADDR_GAIN2           ;
    const uint32_t EEPROM_ADDR_FB_ON           ;
    const uint32_t EEPROM_ADDR_DAC_GAIN        ;
    const uint32_t EEPROM_ADDR_DATA_DELAY      ;
    const uint32_t EEPROM_ADDR_SF_0            ;
    const uint32_t EEPROM_ADDR_SF_1            ;
    const uint32_t EEPROM_ADDR_SF_2            ;
    const uint32_t EEPROM_ADDR_SF_3            ;
    const uint32_t EEPROM_ADDR_SF_4            ;
    const uint32_t EEPROM_ADDR_SF_5            ;
    const uint32_t EEPROM_ADDR_SF_6            ;
    const uint32_t EEPROM_ADDR_SF_7            ;
    const uint32_t EEPROM_ADDR_SF_8            ;
    const uint32_t EEPROM_ADDR_SF_9            ;
    const uint32_t EEPROM_ADDR_TMIN            ;
    const uint32_t EEPROM_ADDR_TMAX            ;
    const uint32_t EEPROM_ADDR_SFB             ;
    const uint32_t EEPROM_ADDR_CUTOFF          ;
    const uint32_t EEPROM_ADDR_BIAS_COMP_T1    ;
    const uint32_t EEPROM_ADDR_BIAS_COMP_T2    ;
    const uint32_t EEPROM_ADDR_SFB_1_SLOPE     ;
    const uint32_t EEPROM_ADDR_SFB_1_OFFSET    ;
    const uint32_t EEPROM_ADDR_SFB_2_SLOPE     ;
    const uint32_t EEPROM_ADDR_SFB_2_OFFSET    ;
    const uint32_t EEPROM_ADDR_SFB_3_SLOPE     ;
    const uint32_t EEPROM_ADDR_SFB_3_OFFSET    ;
    int EEPROM_Gain1; int EEPROM_Gain2; int EEPROM_Polarity;
    int EEPROM_FB_ON; int EEPROM_DAC_gain; int EEPROM_Data_delay;
    int EEPROM_Mod_freq; int EEPROM_Wait_cnt; int EEPROM_Err_avg; 
    int EEPROM_Fpga_Q; int EEPROM_Fpga_R;
    int EEPROM_Amp_H; int  EEPROM_Amp_L; int EEPROM_Err_offset; int EEPROM_Err_th; int EEPROM_Const_step;
    int EEPROM_SF0; int EEPROM_SF1; int EEPROM_SF2; int EEPROM_SF3; int EEPROM_SF4;
    int EEPROM_SF5; int EEPROM_SF6; int EEPROM_SF7; int EEPROM_SF8; int EEPROM_SF9; 
    int EEPROM_TMIN; int EEPROM_TMAX; int EEPROM_SFB; int EEPROM_CUTOFF;
    int EEPROM_BIAS_COMP_T1; int EEPROM_BIAS_COMP_T2; int EEPROM_SFB_1_SLOPE; int EEPROM_SFB_1_OFFSET; 
    int EEPROM_SFB_2_SLOPE; int EEPROM_SFB_2_OFFSET; int EEPROM_SFB_3_SLOPE; int EEPROM_SFB_3_OFFSET;  

     // Constructor
    eeprom_obj(uint32_t add) :
        EEPROM_ADDR_MOD_FREQ(add),
        EEPROM_ADDR_WAIT_CNT(add + 1),
        EEPROM_ADDR_ERR_AVG (add + 2),
        EEPROM_ADDR_MOD_AMP_H (add + 3),
        EEPROM_ADDR_MOD_AMP_L (add + 4),
        EEPROM_ADDR_ERR_TH  (add + 5),
        EEPROM_ADDR_ERR_OFFSET(add + 6),
        EEPROM_ADDR_POLARITY(add + 7),
        EEPROM_ADDR_CONST_STEP(add + 8),
        EEPROM_ADDR_FPGA_Q  (add + 9),
        EEPROM_ADDR_FPGA_R  (add + 10),
        EEPROM_ADDR_GAIN1   (add + 11),
        EEPROM_ADDR_GAIN2   (add + 12),
        EEPROM_ADDR_FB_ON   (add + 13),
        EEPROM_ADDR_DAC_GAIN(add + 14),
        EEPROM_ADDR_DATA_DELAY(add + 15),
        EEPROM_ADDR_SF_0    (add + 16),
        EEPROM_ADDR_SF_1    (add + 17),
        EEPROM_ADDR_SF_2    (add + 18),
        EEPROM_ADDR_SF_3    (add + 19),
        EEPROM_ADDR_SF_4    (add + 20),
        EEPROM_ADDR_SF_5    (add + 21),
        EEPROM_ADDR_SF_6    (add + 22),
        EEPROM_ADDR_SF_7    (add + 23),
        EEPROM_ADDR_SF_8    (add + 24),
        EEPROM_ADDR_SF_9    (add + 25),
        EEPROM_ADDR_TMIN    (add + 26),
        EEPROM_ADDR_TMAX    (add + 27),
        EEPROM_ADDR_SFB     (add + 28),
        EEPROM_ADDR_CUTOFF  (add + 29),
        EEPROM_ADDR_BIAS_COMP_T1(add + 30),
        EEPROM_ADDR_BIAS_COMP_T2(add + 31),
        EEPROM_ADDR_SFB_1_SLOPE (add + 32),
        EEPROM_ADDR_SFB_1_OFFSET(add + 33),
        EEPROM_ADDR_SFB_2_SLOPE (add + 34),
        EEPROM_ADDR_SFB_2_OFFSET(add + 35),
        EEPROM_ADDR_SFB_3_SLOPE (add + 36),
        EEPROM_ADDR_SFB_3_OFFSET(add + 37){}
};

eeprom_obj eeprom_x(EEPROM_BASEADDR_X), eeprom_y(EEPROM_BASEADDR_Y), eeprom_z(EEPROM_BASEADDR_Z);



#endif