name: Compile Examples
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - fqbn: arduino:avr:nano
            platforms: |
              - name: arduino:avr
          - fqbn: arduino:sam:arduino_due_x_dbg
            platforms: |
              - name: arduino:sam
          - fqbn: STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_L476RG
            platforms: |
              - source-url: https://github.com/stm32duino/BoardManagerFiles/raw/master/package_stmicroelectronics_index.json
                name: STMicroelectronics:stm32
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}